#### AZURE OpenAI configs NEW ####
AZURE_OPENAI_API_KEY  = ''
AZURE_OPENAI_ENDPOINT = ""
AZURE_OPENAI_API_VERSION = "2023-05-15"
AZURE_DEPLOYMENT = "gpt4-8k-srinid"

EMBEDDINGS_MODEL="text-embedding-ada-002"
EMBEDDINGS_DEPLOYMENT="text-embedding-ada-002"
EMBEDDINGS_API_KEY=""
EMBEDDINGS_ENDPOINT=''
EMBEDDINGS_API_VERSION="2023-05-15"

Tokens_Count = 8000
